d0_m0_path: /home/enrico/data_dare_test/Data/d0_m0.pkl 
events_path: /home/enrico/data_dare_test/Data/events_list_std_2.pkl
P0_gen_path: /home/enrico/data_dare_test/Data/P0_general_std.csv
cods_labs_path: /home/enrico/data_dare_test/Data/cods_labs.json
cods_lists_path: /home/enrico/data_dare_test/Data/cods_lists.json
config_path: /home/enrico/DARE/Dare/Configs/configs_std.yaml
idps_tests: /home/enrico/data_dare_test/Data/idps_for_tests.pkl
